apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-case-controller
  namespace: {{ include "namespace" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-case-controller
  template:
    metadata:
      labels:
        app: test-case-controller
    spec:
      containers:
        - name: controller
          image: {{ .Values.controller.image }}
          imagePullPolicy: {{ .Values.controller.imagePullPolicy | default "IfNotPresent" }}
          env:
            - name: REMOTE_URL
              value: "http://chrome-node-service:4444"
          command: ["sleep", "infinity"]
