apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: chrome-node-hpa
  namespace: {{ include "namespace" . }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: chrome-node
  minReplicas: {{ .Values.chromeNode.nodeCount }}
  maxReplicas: {{ .Values.chromeNode.maxNodes }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
