apiVersion: v1
kind: ServiceAccount
metadata:
  name: insider-testops-sa
  namespace: {{ include "namespace" . }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: insider-testops-role
  namespace: {{ include "namespace" . }}
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/exec", "pods/log"]
    verbs: ["get", "list", "create", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: insider-testops-binding
  namespace: {{ include "namespace" . }}
subjects:
  - kind: ServiceAccount
    name: insider-testops-sa
roleRef:
  kind: Role
  name: insider-testops-role
  apiGroup: rbac.authorization.k8s.io
