namespace: insider-testops

controller:
  image: <account-id>.dkr.ecr.eu-west-1.amazonaws.com/insider-repo:test-case-controller-1.0.1
  imagePullPolicy: IfNotPresent

chromeNode:
  image: <account-id>.dkr.ecr.eu-west-1.amazonaws.com/insider-repo:chrome_node-142.0
  imagePullPolicy: IfNotPresent
  nodeCount: 1
  maxNodes: 5
